### ISSUE TITLE
Data Types and Format: blank cells 

### ISSUE THREAD

**Issue by dsihi** [JoshuaRady/FOSS_EcoForce5_DMP#2]
Can we change "0" to "-9999" for blank cells under Data Types and Format like below?

"blank cells (use -9999 or NA as appropriate)". 

"0" is data in some cases (GHG Fluxes from soil and ecosystem).

**Comment by JoshuaRady** [comment]
That makes sense.  I have made a change to clarify this.

**Comment by dsihi** [comment]
Looks good!
